
server:
  port: ${custom_port:8086}
  
spring:
  application:
    name: ${application_name:TrainingService}

  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port:5672}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    queue-listener: ${rabbitmq_queue:BatchData-Queue}

  datasource:
    driverClassName: ${datasource_driverClassName:org.postgresql.Driver}
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    
  jpa:
    properties:
      hibernate:
        dialect: ${jap_properties_hibernate_dialect:org.hibernate.dialect.PostgreSQLDialect}
     
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}

  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:${server.port}