
server:
  port: 8086
  
spring:
  rabbitmq:
    port: 5672
    host: ec2-3-128-80-159.us-east-2.compute.amazonaws.com
    username: guest2 
    password: "PvVf2pk&X9Xm%3"

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${REVATURE_POSTGRES_URL}:5432/${REVATURE_POSTGRES_DB}?
    username: ${REVATURE_POSTGRES_USERNAME}
    password: ${REVATURE_POSTGRES_PASSWORD}
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format-sql: true
     
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false